codecov:
  branch: latest
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "75...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  branches:
    - latest
    - latest-next
    - next
    - beta
    - alpha
