version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    assignees:
      - "josh-hemphill"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "development"
    labels:
      - "npm"
      - "dev-dep"
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    assignees:
      - "josh-hemphill"
    open-pull-requests-limit: 1
    allow:
      - dependency-type: "production"
    labels:
      - "npm"
      - "triage"
      - "dep"
  - package-ecosystem: "github-actions"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
    assignees:
      - "josh-hemphill"
    open-pull-requests-limit: 1
    labels:
      - "actions"
      - "triage"
      - "dep"
