name: CodeCov
on:
  push:
    branches:
      - latest
      - latest-next
      - next
      - beta
      - alpha
      - "*.x" # maintenance releases branches

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          # - 16 # Becomes active in early April 2021

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: npm i -g codecov
      - run: npm run cov:send
